package instagram

import (
	"crypto/tls"
	"encoding/json"
	"io"
	"net/http"
	"regexp"
	"strconv"
	"strings"

	"github.com/bwmarrin/discordgo"
)

type gallery struct {
	CurrentIdx int
	Gallery    []string
}

var redditCache = map[string]*gallery{}

var regex, _ = regexp.Compile(`^((?:(?:(?:https):(?://)+)(?:www\.)?)(?:instagram)\.com/p/.+)$`)

func MessageCreate(s *discordgo.Session, m *discordgo.MessageCreate) {
	match := regex.FindStringSubmatch(m.Content)
	if len(match) == 0 {
		return
	}

	imageLink, title, err := postData(match[0], m.Message)
	if err != nil {
		s.ChannelMessageSendReply(m.ChannelID, err.Error(), &discordgo.MessageReference{GuildID: m.GuildID, ChannelID: m.ChannelID, MessageID: m.ID})
		return
	}

	embed := discordgo.MessageEmbed{
		Title: title,
		URL:   match[1],
		Color: 0xffcc00,
		Image: &discordgo.MessageEmbedImage{
			URL: imageLink,
		},
		Fields: []*discordgo.MessageEmbedField{
			{
				Name:   "Original Poster",
				Value:  m.Author.Mention(),
				Inline: true,
			},
		},
		Footer: &discordgo.MessageEmbedFooter{
			Text: "by rogue#0001",
		},
	}

	msg, err := s.ChannelMessageSendEmbed(m.ChannelID, &embed)
	if err != nil {
		return
	}

	if entry, ok := redditCache[m.GuildID+m.ChannelID+m.ID]; ok {
		// transfer the gallery cache of the original message to the new one(the embed)
		redditCache[msg.GuildID+msg.ChannelID+msg.ID] = &gallery{
			CurrentIdx: entry.CurrentIdx,
			Gallery:    entry.Gallery,
		}

		// for some reason, sometimes the page field doesn't appear in the sent message
		// so we have to check for the amount of fields and add the missing one if need be
		for len(msg.Embeds[0].Fields) < 2 {
			msg.Embeds[0].Fields = append(msg.Embeds[0].Fields, &discordgo.MessageEmbedField{
				Name:   "Page",
				Value:  strconv.Itoa(entry.CurrentIdx+1) + "/" + strconv.Itoa(len(entry.Gallery)),
				Inline: true,
			})

			msg, err = s.ChannelMessageEditEmbeds(msg.ChannelID, msg.ID, msg.Embeds)
			if err != nil {
				s.ChannelMessageSendReply(m.ChannelID, err.Error(), &discordgo.MessageReference{GuildID: m.GuildID, ChannelID: m.ChannelID, MessageID: m.ID})
				return
			}
		}

		s.MessageReactionAdd(msg.ChannelID, msg.ID, string([]rune{11013, 65039}))
		s.MessageReactionAdd(msg.ChannelID, msg.ID, string([]rune{10145, 65039}))

		// delete original message, as we don't need it anymore
		delete(redditCache, m.GuildID+m.ChannelID+m.ID)
	}

	s.ChannelMessageDelete(m.ChannelID, m.ID)
}

func MessageReactionAdd(s *discordgo.Session, m *discordgo.MessageReactionAdd) {
	// right and left arrow emojis in rune format
	if m.Emoji.APIName() != string([]rune{10145, 65039}) && m.Emoji.APIName() != string([]rune{11013, 65039}) {
		return
	}

	msg, err := s.ChannelMessage(m.ChannelID, m.MessageID)
	if err != nil {
		s.ChannelMessageSendReply(m.ChannelID, err.Error(), &discordgo.MessageReference{GuildID: m.GuildID, ChannelID: m.ChannelID, MessageID: m.MessageID})
		return
	}
	msg.GuildID = m.GuildID // ChannelMessage returns Message with empty GuildID

	if !ValidateEmbed(msg.Embeds) {
		return
	}

	// the gallery cache gets wiped when the bot is turned off, so we have to rebuild it
	if _, ok := redditCache[msg.GuildID+msg.ChannelID+msg.ID]; !ok {
		api, err := urlData(msg.Embeds[0].URL)
		if err != nil {
			s.ChannelMessageSendReply(m.ChannelID, err.Error(), &discordgo.MessageReference{GuildID: m.GuildID, ChannelID: m.ChannelID, MessageID: m.MessageID})
			return
		} else if !buildGallery(api, msg, true) {
			return
		}
	}

	if entry, ok := redditCache[msg.GuildID+msg.ChannelID+msg.ID]; ok {
		// right arrow
		if m.Emoji.APIName() == string([]rune{10145, 65039}) {
			entry.CurrentIdx++
			if entry.CurrentIdx > len(entry.Gallery)-1 {
				entry.CurrentIdx = 0
			}
		} else {
			entry.CurrentIdx--
			if entry.CurrentIdx < 0 {
				entry.CurrentIdx = len(entry.Gallery) - 1
			}
		}

		msg.Embeds[0].Image.URL = entry.Gallery[entry.CurrentIdx]
		msg.Embeds[0].Fields[1].Value = strconv.Itoa(entry.CurrentIdx+1) + "/" + strconv.Itoa(len(entry.Gallery))
		s.ChannelMessageEditEmbeds(msg.ChannelID, msg.ID, msg.Embeds)

		s.MessageReactionRemove(m.ChannelID, m.MessageID, m.Emoji.APIName(), m.UserID)
	}
}

func buildGallery(api AutoGenerated, m *discordgo.Message, rebuild bool) bool {
	redditCache[m.GuildID+m.ChannelID+m.ID] = &gallery{}

	if entry, ok := redditCache[m.GuildID+m.ChannelID+m.ID]; ok {
		for _, item := range api.Graphql.ShortcodeMedia.EdgeSidecarToChildren.Edges {
			entry.Gallery = append(entry.Gallery, item.Node.DisplayURL)
		}
	}

	// when rebuilding, match current index in the rebuilt cache to the current image in the embed
	if rebuild {
		if entry, ok := redditCache[m.GuildID+m.ChannelID+m.ID]; ok {
			for i := 0; i < len(entry.Gallery); i++ {
				if entry.Gallery[i] == m.Embeds[0].Image.URL {
					entry.CurrentIdx = i
					break
				}
			}
		}
	}

	return true
}

func ValidateEmbed(embeds []*discordgo.MessageEmbed) bool {
	if len(embeds) == 0 {
		return false
	}

	return len(regex.FindStringSubmatch(embeds[0].URL)) != 0
}

func urlData(url string) (AutoGenerated, error) {
	apiJSON := AutoGenerated{}
	url = strings.Split(url, "?")[0] + "?__a=1&__d=dis"

	// https://www.reddit.com/r/redditdev/comments/uncu00/comment/i8gyfm
	client := &http.Client{
		Transport: &http.Transport{
			TLSClientConfig: &tls.Config{},
		},
	}
	req, _ := http.NewRequest("GET", url, nil)
	req.Header.Set("User-agent", "starboard-go")

	res, err := client.Do(req)
	if err != nil {
		return apiJSON, err
	}

	resData, err := io.ReadAll(res.Body)
	if err != nil {
		return apiJSON, err
	}

	err = json.Unmarshal(resData, &apiJSON)
	if err != nil {
		return apiJSON, err
	}

	return apiJSON, nil
}

func postData(url string, msg *discordgo.Message) (string, string, error) {
	api, err := urlData(url)
	if err != nil {
		return "", "", err
	}

	if len(api.Graphql.ShortcodeMedia.EdgeSidecarToChildren.Edges) > 0 {
		// EdgeSidecarToChildren is ordered
		url = api.Graphql.ShortcodeMedia.EdgeSidecarToChildren.Edges[0].Node.DisplayURL

		buildGallery(api, msg, false)
	} else {
		url = api.Graphql.ShortcodeMedia.DisplayURL
	}

	return url, api.Graphql.ShortcodeMedia.Owner.FullName, nil
}
