package reddit

// https://mholt.github.io/json-to-go/
type AutoGenerated []struct {
	Data struct {
		Children []struct {
			Data struct {
				IsGallery           bool        `json:"is_gallery,omitempty"`
				Title               string      `json:"title,omitempty"`
				URLOverriddenByDest string      `json:"url_overridden_by_dest,omitempty"`
				MediaMetadata       interface{} `json:"media_metadata,omitempty"`
				GalleryData         struct {
					Items []struct {
						MediaID string `json:"media_id,omitempty"`
						ID      int    `json:"id,omitempty"`
					} `json:"items,omitempty"`
				} `json:"gallery_data,omitempty"`
				Preview struct {
					Images []struct {
						Source struct {
							URL string `json:"url,omitempty"`
						} `json:"source,omitempty"`
					} `json:"images,omitempty"`
				} `json:"preview,omitempty"`
				IsVideo bool `json:"is_video,omitempty"`
			} `json:"data,omitempty"`
		} `json:"children,omitempty"`
	} `json:"data,omitempty"`
}

func mediaMetadataByID(MediaMetadata interface{}, ID string) string {
	// i'd get fired for this, probably...
	return MediaMetadata.(map[string]interface{})[ID].(map[string]interface{})["s"].(map[string]interface{})["u"].(string)
}
